### ISSUE TITLE
time.Time conversion generates boilergql.TimeTimeToTime()

### ISSUE THREAD

**Issue by troian** [web-ridge/utils-go#7] opened 2020-05-20 17:20 UTC
```go
		ID:        m.ID,
		StartsAt:  boilergql.TimeTimeToTime(m.StartsAt),
		EndsAt:    boilergql.TimeTimeToTime(m.EndsAt),
```

expected
```go
		ID:        m.ID,
		StartsAt:  m.StartsAt,
		EndsAt:    m.EndsAt,
```

**Comment by RichardLindhout** [comment] 2020-05-20 17:38
Are both times exactly the same type?

**Comment by RichardLindhout** [comment] 2020-05-20 17:38
Based on TimeTimeToTime they are

**Comment by RichardLindhout** [comment] 2020-05-20 17:38
Strange, looking into it!

**Comment by troian** [comment] 2020-05-20 17:44
Yah, types are equal

**Comment by RichardLindhout** [comment] 2020-05-20 17:46
It should skip these as custom convert since type should be the same here
https://github.com/web-ridge/gqlgen-sqlboiler/blob/master/convert.go#L814

Just to be sure I did not know gqglen supported go timestamps when will they be generated?

**Comment by RichardLindhout** [comment] 2020-05-20 17:47
So I can test if it's fixed. It generates as Int for me a.t.m. maybe we should change in sqlboiler-graphql-schema too.

**Comment by troian** [comment] 2020-05-20 17:49
Thats what I have in gqlgen.yml
```
models:
  GeoPoint:
    model:
      - github.com/web-ridge/utils-go/boilergql.GeoPoint
  DateTime:
    model:
      - github.com/99designs/gqlgen/graphql.Time
```

and graphql.schema uses them like
```
scalar GeoPoint
scalar DateTime

type Type {
    startsAt: DateTime
    endsAt: DateTime
    createdAt: DateTime
    updatedAt: DateTime
}

```

**Comment by troian** [comment] 2020-05-20 17:50
`gqlgen` supports time.Time https://github.com/99designs/gqlgen/blob/master/graphql/time.go

**Comment by RichardLindhout** [comment] 2020-05-20 18:21
Ok, I'm working on createdAt, updatedAt too a.t.m. will hopefully be able to reproduce this bug this evening and release a new version!

**Comment by RichardLindhout** [comment] 2020-05-20 18:23
Maybe you can speedup this process I need more types to ignore in input but multiple ignores like this do not work https://github.com/web-ridge/sqlboiler-graphql-schema
--skip-input-fields=organizationId,createdAt,updatedAt

have you used multiple ignores yet?

**Comment by troian** [comment] 2020-05-20 18:26
I haven't. Going to try

**Comment by RichardLindhout** [comment] 2020-05-20 18:32
I found it

**Comment by RichardLindhout** [comment] 2020-05-20 18:32
Needs to be this I'll update documentation for that and going on with the timestamp!

**Comment by RichardLindhout** [comment] 2020-05-20 18:53
<-- forgot cli snippet: Needs to be this --skip-input-fields=organizationId --skip-input-fields=createdAt --skip-input-fields=updatedAt

I'm up and running but I need to add some extra changes since timestamps are nullable in database a.t.m.

**Comment by RichardLindhout** [comment] 2020-05-20 18:57
Interesting it should return time.Time but it returns *Time which is the root problem
![Schermafbeelding 2020-05-20 om 20 56 49](https://user-images.githubusercontent.com/6492229/82485931-7125b280-9adc-11ea-9720-ab4d59c979f3.png)

**Comment by RichardLindhout** [comment] 2020-05-20 19:16
Root cause discovered adding fix + test to resolve this
![Schermafbeelding 2020-05-20 om 21 15 33](https://user-images.githubusercontent.com/6492229/82487716-104ba980-9adf-11ea-8535-beffbcef505b.png)

**Comment by RichardLindhout** [comment] 2020-05-20 19:29
One side effect we need to update this repo with also TimeTime on grapql side. It looks a little strange but it will work with future packages too

**Comment by RichardLindhout** [comment] 2020-05-20 19:42
Released https://github.com/web-ridge/gqlgen-sqlboiler/releases

**Comment by RichardLindhout** [comment] 2020-05-20 19:51
You also need to update this package since there will be changes to conversion functions
-->
https://github.com/web-ridge/utils-go/commit/fca24e73632b70a05efe64859cdfc3925ce510b6

**Comment by RichardLindhout** [comment] 2020-05-20 19:54
So updating to

github.com/web-ridge/utils-go@v2.0.7
github.com/web-ridge/gqlgen-sqlboiler@v2.0.13

Should fix this bug

**Comment by troian** [comment] 2020-05-20 20:04
Thats with the latest release. `Time.TimeToMods`
```
	queryMods = append(queryMods, Time.TimeToMods(m.StartsAt, models.AppointmentParticipantColumns.StartsAt)...)
	queryMods = append(queryMods, Time.TimeToMods(m.EndsAt, models.AppointmentParticipantColumns.EndsAt)...)
```

**Comment by RichardLindhout** [comment] 2020-05-20 20:12
Oh my bad.. will fix this.

You have TimeFilter in your schema added then or not?

It will become TimeDotTimeToMods

**Comment by RichardLindhout** [comment] 2020-05-20 20:14
https://github.com/web-ridge/utils-go/releases/tag/v2.0.8

**Comment by RichardLindhout** [comment] 2020-05-20 20:17
Sorry I ment: https://github.com/web-ridge/gqlgen-sqlboiler/releases

**Comment by troian** [comment] 2020-05-20 20:20
`TimeDotTimeToMods` not generated
```
	queryMods = append(queryMods, TimeDotTimeToMods(m.StartsAt, models.AppointmentParticipantColumns.StartsAt)...)
	queryMods = append(queryMods, TimeDotTimeToMods(m.EndsAt, models.AppointmentParticipantColumns.EndsAt)...)
```

**Comment by RichardLindhout** [comment] 2020-05-20 20:30
Please add TimeDotTimeToMods add it as a filter_custom.go in your helpers package like this we need to do more work to support all gqlgen scalars and/or custom scalars + enums in filtering.

It need some more polishing and I don't think I have time this month but will invest more next month in new features. I'm not sure this will be first but I think also in improving merging or overriding functions and adding support for multiple schema.graphql so you can opt-out for some schema's not sure yet.

We want to support this so I created some issues in both repositories to improve the custom scalars
https://github.com/web-ridge/sqlboiler-graphql-schema/issues/7
https://github.com/web-ridge/gqlgen-sqlboiler/issues/28

**Comment by RichardLindhout** [comment] 2020-05-20 20:30
Like this it should work, let me know if it does not.

![Schermafbeelding 2020-05-20 om 22 26 05](https://user-images.githubusercontent.com/6492229/82494197-80f7c380-9ae9-11ea-93ab-8ca93739ccdc.png)

**Comment by RichardLindhout** [comment] 2020-05-20 20:31
filter_custom.go so it will not be overridden when you convert again ;)

**Comment by RichardLindhout** [comment] 2020-05-21 11:49
Closing in favor of the issues
web-ridge/sqlboiler-graphql-schema#7
web-ridge/gqlgen-sqlboiler#28

**Closed as completed by RichardLindhout** 2020-05-21 11:49 UTC
Labels: bug
